title : Kusino Lusdiantoro A.Md.Kes
# logo : /assets/img/headshot_circle.png
description: Medical Record and Health Information | Email: kusino72@gmail.com
# show download : true
theme : jekyll-theme-minimal
