title: Kusino Lusdiantoro A.Md.Kes
logo: /assets/portfolio_uus.png
description: Healthcare Data Analyst | Medical Coding Expert | Passionate about Accurate and Efficient Healthcare Information Management | Claims Processing | Healthcare Data Systems and EHR Management
# show_downloads: true
theme: jekyll-theme-minimal

# Custom styles
sass:
  style: compressed

# Add this in your custom CSS section or a new CSS file
custom_css: true
