title : Kusino Lusdiantoro A.Md.Kes
# logo : /assets/img/headshot_circle.png
description: Medical Record and Health Information  
Instagram : @ksnlsdntr  
Email : kusino72@gmail.com  
# show download : true
theme : jekyll-theme-minimal
