title: Kusino Lusdiantoro A.Md.Kes
# logo: /assets/portfolio_uus.png
description: Healthcare Data Analyst | Medical Coding Expert | Passionate About Accurate and Efficient Health Information Management | Claims Processing | Healthcare Data Systems and EHR Management
# show_downloads: true
theme: jekyll-theme-minimal
