title: Kusino Lusdiantoro A.Md.Kes
logo: /assets/circle2.png
description: Healthcare Data Analyst | Medical Coding Expert | Claims Processing | Healthcare Data Systems and EHR Management | Passionate about Accurate and Efficient Healthcare Information Management
# show_downloads: true
theme: jekyll-theme-minimal
social: 
instagram: "https://instagram.com/ksnlsdntr"
